### PR TITLE
multi: Move script syncing to stakepoold

### LINKED ISSUE #613: stakepoold: Make startup redeem script checking more efficient
More discussion here: #606 

Currently scripts are gathered from all wallets and compared against each other. It should be possible to get all addresses and scripts from the database and have stakepoold compare addresses fetched from dcrwallet to the database results and import the scripts they need independently. I do not think stakepooldclient needs to do any work at all. Only stop on and report errors. 

stakepoold will work without having a connection to a database, which must be changed in order for this to be effective.

The code in question is here:

https://github.com/decred/dcrstakepool/blob/3394b5069f4b459435e5c9fcfb56ecd1929a767c/stakepooldclient/stakepooldclient.go#L348-L435

and stakepoold's ListScripts command.

### PR DESCRIPTION
**Pull request by JoeGruffins**
closes #613  

Remove grpc methods ImportMissingScripts and ListScripts. Stakepoold now
require a connection to a mysql database in order obtain user
preferences which include a list of redeem scripts and heights
registered. Upon start-up, all scripts found in the database but not in
dcrwallet are imported. Remove user config save file as all data will
come from the database.

This is an alternative to ~#606~ #619

### CODE REVIEW

**Comment by chappjc** [comment]
I always thought we wanted to get rid of the stakepoold-mysql connection.  stakepoold already requires a mysql connection, no?  I'm confused by the comment in https://github.com/decred/dcrstakepool/pull/606#issuecomment-597964050 because the last release of stakepoold definitely connects to mysql, and I never liked that.

**Comment by chappjc** [comment]
Is a stakepoold-mysql connection only used presently when `--norpclisten` is enabled?

**Comment by chappjc** [comment]
I'm strongly in favor of https://github.com/decred/dcrstakepool/pull/606 if it works too.  What are the pros and cons of each solution (this PR vs. https://github.com/decred/dcrstakepool/pull/606).

**Comment by chappjc** [comment]
See also https://github.com/decred/dcrstakepool/issues/495, which I think makes a very strong case, and https://github.com/decred/dcrstakepool/issues/134 for historical context.

**Comment by JoeGruffins** [comment]
I left my thoughts about connecting mysql and stakepoold in #495 

You can see in this code that cutting out the middle man for this one instance has also cut the needed code in half.

However, if this indeed causes a security issue, I will work on another implementation using addressesbyaccount. Security is most important.

**Comment by itswisdomagain** [comment]
> However, if this indeed causes a security issue, I will work on another implementation using addressesbyaccount. Security is most important.

I made an implementation using `getaddressesbyaccount` a while ago. I think I'll just create a PR for it and throw it into the mix for consideration.

**Pull request closed without merging**
