### PR TITLE
go.mod: update to protogen version 3

### PR DESCRIPTION
**Pull request by JoeGruffins**
This updates the golang protobuff package to use version 3

https://github.com/golang/protobuf/releases

When I first tried to use the .regen script to make our api.pb.go I was confused by the created go file having the constant const _ = proto.ProtoPackageIsVersion3 and finally found the answer to be downgrading my golang protoc version to v1.2.0. I believe we discussed this @jholdstock ?  
This pr will allow us to use the latest protoc.  I have compiled and bought some tickets with this, without updating stakepoold, and it seems to be going fine.  I will test some more to make sure there are no problems with updating this.

### CODE REVIEW

**Comment by jholdstock** [comment]
This is working well for me using

- go 1.12.7
- libprotoc 3.4.0
- protoc-gen-go 1.3.2

I'd be happy to merge this. My only recommendation would be to update the requirements section of README.md to indicate suggested versions of the above tools.

**Comment by JoeGruffins** [comment]
Does the user need to worry about libprotoc and protoc-gen-go? I think it's only if you need to regenerate the api.pg.go file, which a user doesn't need to do.  Shall we up the recommended go version? I'm of the mind that newer is better.

**Comment by jholdstock** [comment]
Hmm.. interesting point - the current README is a mix of developer information and operator information. 

I want to help others avoid the situation you encountered (incorrect tool versions) and adding the versions to the README seems like a reasonable approach. Maybe we could add this to the [stakepoold README](https://github.com/decred/dcrstakepool/tree/master/backend/stakepoold) instead?


We should definitely update the main README to go version 1.12, but lets do that as a separate task.

**Comment by JoeGruffins** [comment]
I like it under Development, what do you think? I'm not entirely sure those minimal versions are correct. I will double check.
I didn't realized there was a stakepoold readme D:  I will add to it too.

**Comment by jholdstock** [comment]
LGTM

**Comment by JoeGruffins** [comment]
Actually, if the front page readme is fine, I don't think there's a need to put it in the stakepoold readme too.  Just more to update later.  It's also easy to miss that readme.  The tickets I bought are already voting and there doesn't seem to be any problems with communication.  I'm fairly certain the minimums are correct for version 3's of each.

**Comment by dajohi** [comment]
@JoeGruffins rebase needed

**Comment by JoeGruffins** [comment]
@dajohi ok!

**Pull request merged**
