### PR TITLE
[WIP] client/dcrwallet : grpc

### PR DESCRIPTION
**Pull request by JoeGruffins**
related to #512

This sets up up to start using the wallet's grpc.  The structure is almost exactly that which we are using for dcrstakepool <-> stakepoold. This pr only adds the functionality and a version check.

However, there are a few grpc methods missing that would let us do everything we do now.  Namely there doesn't seem to be a ListScripts. In the end this shouldn't be a problem, since I think it will end up that we need to "vote" without the wallet's help.

I did quite a bit of testing with pings and found the behaviour of disconnects and reconnects to behave as expected.  It is all done behind the scenes for us.

I'm still not sure this is the direction we need to go.  Just putting this out there and see what others think.

### CODE REVIEW

**Comment by chappjc** [comment]
Well, I think that moving to gRPC instead of JSON-RPC is the wrong direction personally.  What's the motivation for that?

**Comment by JoeGruffins** [comment]
@chappjc 
1. It seems to have solved connection issues without any extra code.  We also haven't had any problems with it as part of dcrstakepool <-> stakepoold.
2. It's endorsed by "g", newer, and has continued development. Implementing new methods also looks to be less complex.

It's fine if we don't use this, but is there as specific reason why rpc is better, or grpc is lacking?

**Comment by jrick** [comment]
I think grpc is a better rpc protocol, but recently it hasn't received as much love and attention as the json-rpc server in dcrwallet.  This could mean there are some apis you want to use which aren't callable over grpc, but that can be fixed with additions.

If you need to use any kind of notifications, grpc is your only option. the dcrwallet json-rpc server does not produce any notifications.

**Comment by chappjc** [comment]
>     1. It seems to have solved connection issues without any extra code.  We also haven't had any problems with it as part of dcrstakepool <-> stakepoold.

What does this mean "solved connection issues"?  What problem are you trying to solve by converting everything to gRPC?

> It's endorsed by "g", newer, and has continued development. Implementing new methods also looks to be less complex.

I don't count the above as positives.  JSON-RPC is exceedingly simple, so it is to be expected that continued development is not a requirement.  Conversely, I see gRPC as unnecessarily complex (at least for our purposes), with a good deal of moving pieces, which we count as unaudited dependencies, which actually generates unauditable Go code from yet another specification language (protobuf).

**Comment by JoeGruffins** [comment]
@chappjc 
The "connection issues" are those caused by using dcrd/rpcclient. If autoreconnect is turned on a request will block forever by design. But we just want it to fail, so it was necessary to turn off autoreconnect and write our own. By contrast grpc has this behavior by default.

I'm not sure what you mean by the code is not auditable, it's not open source? Or we can't write tests? Do you think it would be prudent then to use rpc for the dcrstakepool<->stakepoold link as well? Why was that design chosen?

**Comment by chappjc** [comment]
> The "connection issues" are those caused by using dcrd/rpcclient. If autoreconnect is turned on a request will block forever by design. But we just want it to fail, so it was necessary to turn off autoreconnect and write our own. By contrast grpc has this behavior by default.

Gotcha.  Although this PR is talking about a dcrwallet link so it wasn't clear if the issue was present with that too.  So gRPC does what when connection is down?  It autoreconnects, but it does not block forever when down?

> I'm not sure what you mean by the code is not auditable, it's not open source? Or we can't write tests? Do you think it would be prudent then to use rpc for the dcrstakepool<->stakepoold link as well? Why was that design chosen?

I mean, do we plan to review every commit made to  google.golang.org/grpc and https://godoc.org/github.com/golang/protobuf?  Also, take a look at the generated code the protoc-go spits out.

**Comment by chappjc** [comment]
Not to say that these are absolute deal breaking issues with gRPC, but it's certainly not a no brainer to switch to it IMO.

**Comment by chappjc** [comment]
As far as why the use of gRPC was chosen for dcrstakepool<->stakepoold... well, you'd have to ask the people who added that, but I wouldn't assume it was a solid decision.

**Comment by JoeGruffins** [comment]
@chappjc 
Using a simple ping for testing, it seems that reconnects are happening as expected behind the scenes and we get an error when dcrwallet is down. "All comms in transient failure" or something like that.

So a
@jrick meh
@chappjc nah
@jholdstock ???
@itswisdomagain ???

**Comment by chappjc** [comment]
Just trying to talk through this still.  What's the real problem **with the dcrwallet RPC connection** that this change is intended to solve?  The change comes at a real cost and with real risks, so there should be a good reason to match.  The chain state and notification issues aren't present with stakepoold->dcrwallet, right?

**Comment by JoeGruffins** [comment]
@chappjc 
The real problem, I think, is just what I previously described.  To be honest, that autoreconnect fix works for me, as far as wallet commands are concerned, but it also seems overly complicated.  We want the client to just do that on its on.  I thought that implementing grpc would simplify the code.  That's all. And we are already using it elsewhere, so it's not adding a dependency. And if that's a problem then it's a bigger problem for dcrwallet, because funds are at stake.

It's true that there is only one stakepoold per wallet, but we don't know if dcrwallet is on the same machine as stakepoold.  Yes it should be but I made a pr about this and it was decided that, we just don't know.  #516 As you can input an ip, this makes sense. 

However, dcrd can't use grpc, so need to do the websocket stuff.  Maybe it would be less work for everyone to go through with the @davecgh suggestion

> I have been thinking for a while that rpcclient probably needs to be reworked in general to just provide the nice bidirectional jsonrpc to concrete types adapter code and leave the connection handling semantics to the consumer.

If that will make it more useful to all of us. It does seem a shame to write a bunch of code over and over...

**Comment by chappjc** [comment]
OK, no more comments from me after this.   I'm just pointing out that the reconnect issues have only ever been a practical concern for the the connection to dcrd, which is _necessarily_ an over the internet in this case, not the wallet (even if an operator wants to make their life difficult by separating stakepoold and dcrwallet with uncontrolled hops on the internet, which by the way is only one extreme reason why rpclisten might need to be not localhost since these processes can be on the same LAN).  

Also I don't see it as overly complicated to have the dcrd reconnect fix (handle reconnect application-side rather than relying on rpcclient's autoreconnect feature) when the alternative is a big dependency that is effectively a black-box (even if it is already used in other places because now it's going to be in yet another spot).

Yes, it is valid to question whether it's a net positive feature for dcrwallet too.  Doesn't mean we should dive in and make the same leap of faith everywhere IMO.

**Comment by chappjc** [comment]
> If that will make it more useful to all of us. It does seem a shame to write a bunch of code over and over...

I said I had my last comment, but I meant to respond to this bit by noting that the application (consumer) knows the best way to handle a lost and reestablished connection.  This is certainly the case when having to deal with chain state and possibly missed notifications from dcrd, although that is not the case in this PR ofc.  For stakepoold->dcrwallet, maybe your right and it's simple enough to just use gRPC.

**Comment by JoeGruffins** [comment]
It would be simpler to just use the current wrapper for dcrwallet and call it a day... If that works.  Perhaps the reconnect back-off could be added. 
I'll wait for the other opinions tho.

**Comment by jholdstock** [comment]
You can put me firmly in the "meh" camp - I see the benefits and drawbacks of both.

Each should be considered on a case-by-case basis. On a personal level I think I prefer gRPC but the overall direction of the project has been away from gRPC and toward JSON.

**Comment by chappjc** [comment]
I've made my opinions about it clear, I think, but really this change isn't such a big deal.  It really may be net positive; I'm not convinced. It's unlikely to hurt vsp functionality.

It's also not me place.  No more push back from me.

**Comment by JoeGruffins** [comment]
I'm going to start on the json-rpc version tomorrow, lol

**Comment by JoeGruffins** [comment]
Thanks everyone who participated in the conversation, especially @chappjc !

**Pull request closed without merging**
